development:
  db:
    uri: "mongodb://localhost/node-mongo-examples"
  facebook:
    appId: "202263326537254"
    appSecret: "f12d943a863da7bd6d27823355769ec5"
    host_uri: "http://localhost:3001"
staging:
  db:
    uri: "mongodb://localhost/noobjs_staging"
  facebook:
    appId: "202263326537254"
    appSecret: "f12d943a863da7bd6d27823355769ec5"
    host_uri: "http://localhost:3001"
production:
  db:
    uri: "mongodb://nodejs:nodejs@staff.mongohq.com:10045/app2591449"
  facebook:
    appId: "202263326537254"
    appSecret: "f12d943a863da7bd6d27823355769ec5"
    host_uri: "http://nodejs-express-demo.herokuapp.com"
